eight commit

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -90,20 +90,23 @@ jobs:
             echo "NODE_ENV=production" > /home/ubuntu/apps/build/configs/.env.production
             echo "PORT=${{secrets.PORT}}" >> /home/ubuntu/apps/build/configs/.env.production
             echo "MONGODB_URL=${{secrets.MONGODB_URL}}" >> /home/ubuntu/apps/build/configs/.env.production
-
       - name: Install Dependencies and Restart Application
         uses: appleboy/ssh-action@master
         with:
-          host: ${{ secrets.SERVER_IP }}
-          username: ${{ secrets.SERVER_USERNAME }}
-          key: ${{ secrets.SSH_PRIVATE_KEY }}
-          port: 22
-          script: |
-            cd /home/ubuntu/apps/build
-            yarn install --production
-            if pm2 show product-service > /dev/null; then
-              echo "Application is running. Restarting..."
-              yarn restart
-            else
-              echo "Application is not running. Starting..."
-              yarn start
+              host: ${{ secrets.SERVER_IP }}
+              username: ${{ secrets.SERVER_USERNAME }}
+              key: ${{ secrets.SSH_PRIVATE_KEY }}
+              port: 22
+              script: |
+                cd /home/ubuntu/apps/build
+                if ! command -v yarn &> /dev/null; then
+                  echo "Yarn not found. Installing yarn..."
+                  npm install -g yarn
+                fi
+                yarn install --production
+                if pm2 show product-service > /dev/null; then
+                  echo "Application is running. Restarting..."
+                  yarn restart
+                else
+                  echo "Application is not running. Starting..."
+                  yarn start
